version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/metis
    steps:
      - checkout:
          path: ~/metis
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.6.5-node
      - image: circleci/postgres:11.2-alpine
        environment:
          POSTGRES_ROOT_PASSWORD: ""
          POSTGRES_DB: my2ndapp_test
          POSTGRES_USER: postgres
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/metis
    steps:
      - checkout:
          path: ~/metis
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

  deploy:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: yarn install
          command: heroku run yarn install -a heroku-metista
      - run:
          name: push docker image
          command: heroku container:push web -a heroku-metista
      - run:
          name: release docker image
          command: heroku container:release web -a heroku-metista
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME
      - run:
          name: webpacker compile
          command: heroku run bundle exec rails webpacker:compile -a heroku-metista

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires: 
            - test
          filters:
            branches:
              only: master