version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/metis
    steps:
      - checkout:
          path: ~/metis
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/postgres:11.2-alpine
        environment:
          POSTGRES_ROOT_PASSWORD: ""
          POSTGRES_DB: my2ndapp_test
          POSTGRES_USER: postgres
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/metis
    steps:
      - checkout:
          path: ~/metis
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build



