default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: ""
  pool: 5

development:
  <<: *default
  database: my2ndapp_development


test:
  <<: *default
  database: my2ndapp_test

production:
  <<: *default
  database: my2ndapp_production
  username: postgres
  password: <%= ENV['MY2NDAPP_DATABASE_PASSWORD'] %>