default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: ""
  pool: 5

development:
  <<: *default
  database: my2ndapp_development


test:
  <<: *default
  database: my2ndapp_test
  host: <%= ENV.fetch("APP_DATABASE_HOST"){ 'db' } %>

production:
  <<: *default
  database: <%= ENV['MY2NDAPP_DATABASE'] %>
  username: <%= ENV['MY2NDAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MY2NDAPP_DATABASE_PASSWORD'] %>
  password: <%= ENV['MY2NDAPP_DATABASE_HOST'] %>